/**/gq7/gq7_driver:
  ros__parameters:
    # This can be set by passing an var to the launch file
    port     : $(var port)
    baudrate : $(var baudrate)

    # Disable the transform from the mount to frame id transform as it should be handled from a URDF file and robot_description
    publish_mount_to_frame_id_transform : False

    # This will cause the node to convert any NED measurements to ENU
    # This will also cause the node to convert any vehicle frame measurements to the ROS definition of a vehicle frame
    use_enu_frame : True

    # Configure some frame IDs
    frame_id          : $(var frame_id)            # Frame ID of all of the filter messages. Represents the location of the GQ& in the tf tree
    earth_frame_id    : "earth"                    # Frame ID of the global frame
    gnss1_frame_id    : $(var gnss1_frame_id)      # Frame ID of GNSS antenna 1. This represents GNSS antenna 1 of the GQ7 in the tf tree
    gnss2_frame_id    : $(var gnss2_frame_id)      # Frame ID of GNSS antenna 2. This represents GNSS antenna 2 of the GQ7 in the tf tree
    target_frame_id   : $(var base_link_frame_id)  # Frame ID that we will publish a transform to.

    # We will use global transform mode, meaning that we will publish the following transforms from this node
    #   earth_frame_id -> target_frame_id
    # This is hard for ROS standard tools to understand, but can be useful for users who do not want to use those tools
    tf_mode: 1

    # Enable the RTK dongle interface for communication with the 3DM-RTK.
    # Note: Even if you do not have a 3DM-RTK connected to the aux port, this boolean can remain true
    rtk_dongle_enable : True

    # If this is enabled, this will connect to the aux port of the GQ7 and listen for RTCM from ROS
    ntrip_interface_enable : $(var ntrip)
    aux_port               : $(var aux_port)
    aux_baudrate           : $(var aux_baudrate)

    # (GQ7 only) Relative Position Configuration
    # Disabled for this use case
    filter_relative_position_config : False

    # Antenna #1 lever arm offset source
    #     0 - Disabled:  We will not configure the antenna offset, or publish it as a transform
    #     1 - Manual:    We will use the provided vector to configure the device, and publish it as the transform between frame_id and gnss1_frame_id
    #     2 - Transform: We will lookup the transform between frame_id and gnss1_frame_id and use it to configure the device. We will ignore gns1_antenna_offset
    # Antenna #1 lever arm offset vector
    #     For GQ7 - in the vehicle frame wrt IMU origin (meters)
    #     For all other models - in the IMU frame wrt IMU origin (meters)
    # Note: Make this as accurate as possible for good performance
    gnss1_antenna_offset_source : $(var gnss1_antenna_offset_source)
    gnss1_antenna_offset        : $(var gnss1_antenna_offset)

    # Antenna #2 lever arm offset source
    #     0 - Disabled:  We will not configure the antenna offset, or publish it as a transform
    #     1 - Manual:    We will use the provided vector to configure the device, and publish it as the transform between frame_id and gnss2_frame_id
    #     2 - Transform: We will lookup the transform between frame_id and gnss2_frame_id and use it to configure the device. We will ignore gns2_antenna_offset
    # Antenna #2 lever arm offset vector
    #     For GQ7 - in the vehicle frame wrt IMU origin (meters)
    #     For all other models - in the IMU frame wrt IMU origin (meters)
    # Note: Make this as accurate as possible for good performance
    gnss2_antenna_offset_source : $(var gnss2_antenna_offset_source)
    gnss2_antenna_offset        : $(var gnss2_antenna_offset)

    # (GQ7 only) Filter Initialization control
    #     Auto-Heading alignment selector (note this is a bitfield, you can use more than 1 source) =
    #         Bit 0 - Dual-antenna GNSS
    #         Bit 1 - GNSS kinematic (requires motion, e.g. a GNSS velocity)
    #         Bit 2 - Magnetometer
    #         Bit 3 - External Heading (first valid external heading will be used to initialize the filter)
    filter_auto_heading_alignment_selector : $(var filter_auto_heading_alignment_selector)

    # For this use case, we will not publish any IMU data
    imu_data_rate : 0

    # For this use case, we will not publish any raw GNSS information
    gnss1_llh_position_data_rate   : 0
    gnss1_velocity_data_rate       : 0
    gnss1_odometry_earth_data_rate : 0
    gnss2_llh_position_data_rate   : 0
    gnss2_velocity_data_rate       : 0
    gnss2_odometry_earth_data_rate : 0

    # We will publish the global position in both ECEF and LLH for this example
    # Also publish the human readable message which can be echoed from the command line
    filter_human_readable_status_data_rate : 1
    filter_llh_position_data_rate          : 50
    filter_odometry_earth_data_rate        : 50
    filter_odometry_map_data_rate          : 0
