# Example parameters showing how one could use IMU data from the GQ7 in robot_localization
/**/ekf_localization:
  ros__parameters:
    imu0: /gq7/imu/data
    imu0_config: [false, false, false,  # X, Y, Z disabled since no position data in IMU
                  false, false, false,  # roll, pitch, yaw disabled since raw IMU data does not have very good attitude estimates
                  false, false, false,  # X, Y, Z velocity disabled since no linear velocity in IMU
                  true, true, true,     # roll, pitch, yaw rates (angular rates) enabled
                  true, true, true]     # X, Y, Z acceleration (linear acceleration) enabled
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true