/**/gq7/gq7_ntrip_client:
  ros__parameters:
    # These can be set by passing args to the launch file
    host       : $(var ntrip_host)
    port       : $(var ntrip_port)
    mountpoint : $(var ntrip_mountpoint)

    # For this example, we will always assume that we are going to authenticate
    authenticate : true
    username : $(var ntrip_username)
    password : $(var ntrip_password)

    # Allow SSL, but do not allow custom certs and keys
    ssl : $(var ntrip_ssl)

    # Since the RTCM will be coming from the RTK base station whose position may be the map frame, set the frame id to map
    rtcm_frame_id : "map"

    # Use the smaller RTCM message option
    rtcm_message_package : "rtcm_msgs"